version: '3.8'

services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile-service1
    deploy:
      replicas: 3
    networks:
      - mynetwork

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service2
    container_name: service2-container
    image: sqjoni/service2
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd:/etc/nginx/.htpasswd
      - ./html:/usr/share/nginx/html
    ports:
      - "8198:8198"
    depends_on:
      - service1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
