version: '3.8'

services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: service1-container
    image: sqjoni/service1
    ports:
      - "8199:8199"
    depends_on:
      - service2
    networks:
      - mynetwork

  service2:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: service2-container
    image: sqjoni/service2
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
