FROM python:3.9-slim

WORKDIR /app

COPY service2.py .

RUN apt-get update && apt-get install -y \
    curl \
    procps \
    && rm -rf /var/lib/apt/lists/*

RUN pip install flask requests

CMD ["python", "service2.py"]